version: '3'
services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ruby /app/worker.rb
    networks:
      - dockernet
    environment:
      - RABBITMQ_HOST=192.168.0.1
      - RABBITMQ_USER=libercapital
      - RABBITMQ_PASSWD=t0ps3kret
      - RABBITMQ_VHOST=libercapital
      - QUEUE_NAME=worker_queue
      - REDIS_HOST=192.168.0.1
networks:
  dockernet:
      external: true
