version: '3'
services:

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    network_mode: "bridge"

  app_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ruby /app/worker.rb
    deploy:
      mode: replicated
      replicas: 3
    environment:
      - RABBITMQ_HOST=localhost
      - QUEUE_NAME=worker_queue
      - REDIS_HOST=localhost
    depends_on:
      - rabbitmq

volumes:
  esdata:
    driver: local
