version: '3'
services:

  redis:
    image: redis:latest
    command: redis-server
    network_mode: "bridge"

  api:
    depends_on:
      - 'redis'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'

volumes:
  esdata:
    driver: local
